site_name: Ducky Documentation
pages:
    - Trang chủ: index.md
    - Bắt đầu:
        - Các quy ước để làm việc với Ducky: begin/coding-style.md
        - Tìm hiểu về URI trong Ducky: begin/ducky-uri.md
        - Cấu trúc thư mục: begin/folder-structure.md
        - Luồng dữ liệu: begin/data-flow.md
    - Lớp:
        - Lớp hệ thống:
            - Lớp View: class/system/view.md
            - Lớp Route: class/system/route.md
            - Lớp Debug: class/system/debug.md
            - Lớp Config: class/system/config.md
theme: readthedocs
site_favicon: favicon.ico
